project_id = "zlzasfhcxcznaprrragl"

[functions.evolution-webhook]
verify_jwt = false

[functions.upload-documents-minio]
verify_jwt = false

[functions.recover-stuck-otp]
verify_jwt = false

[functions.qr-redirect]
verify_jwt = false
